import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import prisma from "@/lib/prisma";

export const maxDuration = 60;
export const dynamic = "force-dynamic";

interface UniSeed { name: string; nameZh: string; country: string; city: string; state?: string; website: string; description: string; type: string; foundedYear: number; studentCount: number; acceptanceRate: number | null; avgSAT?: number; avgACT?: number; avgIELTS?: number; avgTOEFL?: number; avgGPA?: number; tuitionDomestic: number; tuitionInternational: number; livingCost: number; majors: string[]; qsRank?: number; usnewsRank?: number; }

const UNIS: UniSeed[] = [
  { name:"Harvard University",nameZh:"哈佛大学",country:"United States",city:"Cambridge",state:"Massachusetts",website:"https://www.harvard.edu",description:"Harvard University is a private Ivy League research university and the oldest institution of higher learning in the United States.",type:"private",foundedYear:1636,studentCount:31000,acceptanceRate:3.4,avgSAT:1520,avgACT:34,avgIELTS:7.5,avgTOEFL:104,avgGPA:4.18,tuitionDomestic:57261,tuitionInternational:57261,livingCost:19600,majors:["Computer Science","Economics","Psychology","Political Science","Biology","Mathematics","Physics","History","English","Chemistry"],qsRank:4,usnewsRank:1},
  { name:"Massachusetts Institute of Technology",nameZh:"麻省理工学院",country:"United States",city:"Cambridge",state:"Massachusetts",website:"https://www.mit.edu",description:"MIT is a private research university specializing in science, engineering, and technology.",type:"private",foundedYear:1861,studentCount:11934,acceptanceRate:4.0,avgSAT:1540,avgACT:35,avgIELTS:7.5,avgTOEFL:100,avgGPA:4.17,tuitionDomestic:57986,tuitionInternational:57986,livingCost:18300,majors:["Computer Science","Electrical Engineering","Mechanical Engineering","Physics","Mathematics","Chemical Engineering","Aerospace Engineering","Biology"],qsRank:1,usnewsRank:2},
  { name:"Stanford University",nameZh:"斯坦福大学",country:"United States",city:"Stanford",state:"California",website:"https://www.stanford.edu",description:"Stanford University is a private research university in Silicon Valley known for entrepreneurial spirit.",type:"private",foundedYear:1885,studentCount:17300,acceptanceRate:3.7,avgSAT:1510,avgACT:34,avgIELTS:7.5,avgTOEFL:105,avgGPA:4.18,tuitionDomestic:58416,tuitionInternational:58416,livingCost:19500,majors:["Computer Science","Business","Engineering","Biology","Psychology","Economics","Political Science","Mathematics"],qsRank:5,usnewsRank:3},
  { name:"University of Oxford",nameZh:"牛津大学",country:"United Kingdom",city:"Oxford",website:"https://www.ox.ac.uk",description:"The University of Oxford is the oldest university in the English-speaking world with a renowned tutorial system.",type:"public",foundedYear:1096,studentCount:25500,acceptanceRate:17.5,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.7,tuitionDomestic:9250,tuitionInternational:35080,livingCost:14500,majors:["Law","Medicine","PPE","English Literature","Mathematics","Physics","Economics","History","Computer Science"],qsRank:3,usnewsRank:5},
  { name:"University of Cambridge",nameZh:"剑桥大学",country:"United Kingdom",city:"Cambridge",website:"https://www.cam.ac.uk",description:"The University of Cambridge is a collegiate public research university founded in 1209.",type:"public",foundedYear:1209,studentCount:24200,acceptanceRate:21.0,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.7,tuitionDomestic:9250,tuitionInternational:33825,livingCost:14000,majors:["Natural Sciences","Engineering","Mathematics","Economics","Law","Computer Science","Medicine","History"],qsRank:2,usnewsRank:8},
  { name:"California Institute of Technology",nameZh:"加州理工学院",country:"United States",city:"Pasadena",state:"California",website:"https://www.caltech.edu",description:"Caltech is a world-renowned science and engineering institute with exceptional student-to-faculty ratio.",type:"private",foundedYear:1891,studentCount:2400,acceptanceRate:3.9,avgSAT:1545,avgACT:35,avgIELTS:7.5,avgTOEFL:105,avgGPA:4.19,tuitionDomestic:60864,tuitionInternational:60864,livingCost:18400,majors:["Physics","Computer Science","Engineering","Mathematics","Chemistry","Biology","Astronomy"],qsRank:15,usnewsRank:9},
  { name:"ETH Zurich",nameZh:"苏黎世联邦理工学院",country:"Switzerland",city:"Zurich",website:"https://www.ethz.ch",description:"ETH Zurich is a leading public research university in science and technology, producing over 20 Nobel laureates.",type:"public",foundedYear:1855,studentCount:24200,acceptanceRate:27.0,avgSAT:1450,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.6,tuitionDomestic:1460,tuitionInternational:1460,livingCost:17000,majors:["Computer Science","Mechanical Engineering","Physics","Mathematics","Architecture","Electrical Engineering"],qsRank:7,usnewsRank:29},
  { name:"Imperial College London",nameZh:"帝国理工学院",country:"United Kingdom",city:"London",website:"https://www.imperial.ac.uk",description:"Imperial College London focuses exclusively on science, engineering, medicine, and business.",type:"public",foundedYear:1907,studentCount:20500,acceptanceRate:14.3,avgIELTS:6.5,avgTOEFL:92,avgGPA:3.6,tuitionDomestic:9250,tuitionInternational:35100,livingCost:16000,majors:["Engineering","Computer Science","Medicine","Physics","Mathematics","Business"],qsRank:6,usnewsRank:13},
  { name:"University of Chicago",nameZh:"芝加哥大学",country:"United States",city:"Chicago",state:"Illinois",website:"https://www.uchicago.edu",description:"UChicago is known for rigorous academics and the Chicago School of Economics.",type:"private",foundedYear:1890,studentCount:17200,acceptanceRate:5.4,avgSAT:1530,avgACT:34,avgIELTS:7.0,avgTOEFL:104,avgGPA:4.0,tuitionDomestic:63900,tuitionInternational:63900,livingCost:18100,majors:["Economics","Political Science","Mathematics","Physics","Biology","English"],qsRank:11,usnewsRank:6},
  { name:"National University of Singapore",nameZh:"新加坡国立大学",country:"Singapore",city:"Singapore",website:"https://www.nus.edu.sg",description:"NUS is the flagship university of Singapore and consistently ranked as Asia's best.",type:"public",foundedYear:1905,studentCount:38000,acceptanceRate:25.0,avgSAT:1380,avgACT:30,avgIELTS:6.5,avgTOEFL:92,avgGPA:3.5,tuitionDomestic:8200,tuitionInternational:30000,livingCost:12000,majors:["Computer Science","Business","Engineering","Law","Medicine","Architecture"],qsRank:8,usnewsRank:26},
  { name:"Tsinghua University",nameZh:"清华大学",country:"China",city:"Beijing",website:"https://www.tsinghua.edu.cn",description:"Tsinghua is China's top university, excelling in engineering and computer science.",type:"public",foundedYear:1911,studentCount:50000,acceptanceRate:10.0,avgSAT:1400,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.5,tuitionDomestic:5000,tuitionInternational:28000,livingCost:8000,majors:["Computer Science","Engineering","Business","Architecture","Law","Economics"],qsRank:25,usnewsRank:23},
  { name:"Peking University",nameZh:"北京大学",country:"China",city:"Beijing",website:"https://www.pku.edu.cn",description:"Peking University is renowned for humanities, social sciences, and natural sciences.",type:"public",foundedYear:1898,studentCount:45000,acceptanceRate:12.0,avgSAT:1380,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.4,tuitionDomestic:5000,tuitionInternational:26000,livingCost:8000,majors:["Economics","Law","Medicine","Computer Science","Chinese Literature","Mathematics"],qsRank:17,usnewsRank:39},
  { name:"Yale University",nameZh:"耶鲁大学",country:"United States",city:"New Haven",state:"Connecticut",website:"https://www.yale.edu",description:"Yale is an Ivy League known for law, drama, music, and undergraduate liberal arts.",type:"private",foundedYear:1701,studentCount:14600,acceptanceRate:4.5,avgSAT:1515,avgACT:34,avgIELTS:7.5,avgTOEFL:100,avgGPA:4.14,tuitionDomestic:62250,tuitionInternational:62250,livingCost:18100,majors:["Law","Economics","Political Science","History","English","Psychology"],qsRank:16,usnewsRank:11},
  { name:"Princeton University",nameZh:"普林斯顿大学",country:"United States",city:"Princeton",state:"New Jersey",website:"https://www.princeton.edu",description:"Princeton emphasizes undergraduate education with strong engineering and humanities.",type:"private",foundedYear:1746,studentCount:8800,acceptanceRate:4.4,avgSAT:1510,avgACT:34,avgIELTS:7.5,avgTOEFL:100,avgGPA:3.95,tuitionDomestic:57410,tuitionInternational:57410,livingCost:18700,majors:["Computer Science","Economics","Mathematics","Physics","Political Science","English"],qsRank:18,usnewsRank:16},
  { name:"Columbia University",nameZh:"哥伦比亚大学",country:"United States",city:"New York",state:"New York",website:"https://www.columbia.edu",description:"Columbia is an Ivy League university in Manhattan with a famous core curriculum.",type:"private",foundedYear:1754,studentCount:33400,acceptanceRate:3.9,avgSAT:1510,avgACT:34,avgIELTS:7.5,avgTOEFL:100,avgGPA:4.12,tuitionDomestic:65524,tuitionInternational:65524,livingCost:20600,majors:["Economics","Political Science","English","Engineering","Computer Science","Journalism"],qsRank:23,usnewsRank:7},
  { name:"University of Pennsylvania",nameZh:"宾夕法尼亚大学",country:"United States",city:"Philadelphia",state:"Pennsylvania",website:"https://www.upenn.edu",description:"UPenn is an Ivy League founded by Benjamin Franklin, home to Wharton School of Business.",type:"private",foundedYear:1740,studentCount:26200,acceptanceRate:5.9,avgSAT:1500,avgACT:34,avgIELTS:7.0,avgTOEFL:100,avgGPA:4.0,tuitionDomestic:58620,tuitionInternational:58620,livingCost:18200,majors:["Business","Engineering","Nursing","Computer Science","Economics","Biology"],qsRank:12,usnewsRank:15},
  { name:"University of California, Berkeley",nameZh:"加州大学伯克利分校",country:"United States",city:"Berkeley",state:"California",website:"https://www.berkeley.edu",description:"UC Berkeley is the flagship of the UC system, known for academic excellence and activism.",type:"public",foundedYear:1868,studentCount:45200,acceptanceRate:14.4,avgSAT:1430,avgACT:32,avgIELTS:7.0,avgTOEFL:90,avgGPA:4.15,tuitionDomestic:14400,tuitionInternational:48000,livingCost:18200,majors:["Computer Science","Engineering","Economics","Business","Political Science","Biology"],qsRank:10,usnewsRank:4},
  { name:"University of California, Los Angeles",nameZh:"加州大学洛杉矶分校",country:"United States",city:"Los Angeles",state:"California",website:"https://www.ucla.edu",description:"UCLA is one of the most applied-to universities in the U.S., known for film and medicine.",type:"public",foundedYear:1919,studentCount:47600,acceptanceRate:10.8,avgSAT:1410,avgACT:31,avgIELTS:7.0,avgTOEFL:87,avgGPA:4.0,tuitionDomestic:13800,tuitionInternational:47000,livingCost:18400,majors:["Film","Engineering","Business","Psychology","Biology","Computer Science"],qsRank:36,usnewsRank:14},
  { name:"Cornell University",nameZh:"康奈尔大学",country:"United States",city:"Ithaca",state:"New York",website:"https://www.cornell.edu",description:"Cornell is an Ivy League and land-grant university with 'any person, any study' ethos.",type:"private",foundedYear:1865,studentCount:25500,acceptanceRate:8.7,avgSAT:1480,avgACT:33,avgIELTS:7.0,avgTOEFL:100,avgGPA:4.05,tuitionDomestic:63800,tuitionInternational:63800,livingCost:17000,majors:["Engineering","Hotel Management","Agriculture","Computer Science","Architecture","Business"],qsRank:13,usnewsRank:21},
  { name:"University of Toronto",nameZh:"多伦多大学",country:"Canada",city:"Toronto",state:"Ontario",website:"https://www.utoronto.ca",description:"U of T is Canada's largest university, excelling in AI research and medicine.",type:"public",foundedYear:1827,studentCount:93000,acceptanceRate:43.0,avgSAT:1350,avgACT:30,avgIELTS:6.5,avgTOEFL:89,avgGPA:3.6,tuitionDomestic:6100,tuitionInternational:45000,livingCost:15000,majors:["Computer Science","Engineering","Medicine","Business","Psychology","Life Sciences"],qsRank:21,usnewsRank:18},
  { name:"University of Melbourne",nameZh:"墨尔本大学",country:"Australia",city:"Melbourne",state:"Victoria",website:"https://www.unimelb.edu.au",description:"Melbourne is Australia's top university, known for the Melbourne Model curriculum.",type:"public",foundedYear:1853,studentCount:52000,acceptanceRate:30.0,avgIELTS:6.5,avgTOEFL:79,avgGPA:3.3,tuitionDomestic:10000,tuitionInternational:38000,livingCost:16000,majors:["Medicine","Law","Engineering","Business","Arts","Science"],qsRank:14,usnewsRank:27},
  { name:"University of Tokyo",nameZh:"东京大学",country:"Japan",city:"Tokyo",website:"https://www.u-tokyo.ac.jp",description:"Todai is Japan's premier national university, producing prime ministers and Nobel laureates.",type:"public",foundedYear:1877,studentCount:28200,acceptanceRate:34.0,avgSAT:1410,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.5,tuitionDomestic:535800,tuitionInternational:535800,livingCost:12000,majors:["Engineering","Law","Medicine","Economics","Science","Literature"],qsRank:28,usnewsRank:81},
  { name:"University of Edinburgh",nameZh:"爱丁堡大学",country:"United Kingdom",city:"Edinburgh",website:"https://www.ed.ac.uk",description:"Edinburgh is one of Scotland's ancient universities, strong in AI and medicine.",type:"public",foundedYear:1583,studentCount:41000,acceptanceRate:10.0,avgIELTS:6.5,avgTOEFL:92,avgGPA:3.4,tuitionDomestic:9250,tuitionInternational:28950,livingCost:13000,majors:["Computer Science","Medicine","Law","Engineering","Literature","Philosophy"],qsRank:22,usnewsRank:34},
  { name:"University of Michigan",nameZh:"密歇根大学安娜堡分校",country:"United States",city:"Ann Arbor",state:"Michigan",website:"https://www.umich.edu",description:"Michigan is a top public research university with strong engineering and athletics.",type:"public",foundedYear:1817,studentCount:50000,acceptanceRate:20.0,avgSAT:1440,avgACT:32,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.9,tuitionDomestic:17200,tuitionInternational:56500,livingCost:14000,majors:["Engineering","Business","Computer Science","Psychology","Economics","Medicine"],qsRank:30,usnewsRank:17},
  { name:"Northwestern University",nameZh:"西北大学",country:"United States",city:"Evanston",state:"Illinois",website:"https://www.northwestern.edu",description:"Northwestern is known for journalism, engineering, and performing arts on Lake Michigan.",type:"private",foundedYear:1851,studentCount:23000,acceptanceRate:7.0,avgSAT:1490,avgACT:33,avgIELTS:7.5,avgTOEFL:100,avgGPA:4.1,tuitionDomestic:63468,tuitionInternational:63468,livingCost:18200,majors:["Journalism","Engineering","Business","Communication","Economics","Theater"],qsRank:32,usnewsRank:24},
  { name:"Duke University",nameZh:"杜克大学",country:"United States",city:"Durham",state:"North Carolina",website:"https://www.duke.edu",description:"Duke is known for law, medicine, business, public policy, and Division I athletics.",type:"private",foundedYear:1838,studentCount:17200,acceptanceRate:5.9,avgSAT:1500,avgACT:34,avgIELTS:7.0,avgTOEFL:100,avgGPA:4.0,tuitionDomestic:63450,tuitionInternational:63450,livingCost:18300,majors:["Public Policy","Economics","Biology","Engineering","Computer Science","Law"],qsRank:34,usnewsRank:22},
  { name:"Johns Hopkins University",nameZh:"约翰霍普金斯大学",country:"United States",city:"Baltimore",state:"Maryland",website:"https://www.jhu.edu",description:"JHU is America's first research university, renowned for medicine and international studies.",type:"private",foundedYear:1876,studentCount:29200,acceptanceRate:7.5,avgSAT:1505,avgACT:34,avgIELTS:7.0,avgTOEFL:100,avgGPA:4.0,tuitionDomestic:60480,tuitionInternational:60480,livingCost:17800,majors:["Medicine","Public Health","International Relations","Engineering","Biology","Neuroscience"],qsRank:29,usnewsRank:10},
  { name:"UCL",nameZh:"伦敦大学学院",country:"United Kingdom",city:"London",website:"https://www.ucl.ac.uk",description:"UCL was the first university in England to admit students regardless of religion.",type:"public",foundedYear:1826,studentCount:45000,acceptanceRate:12.0,avgIELTS:6.5,avgTOEFL:92,avgGPA:3.4,tuitionDomestic:9250,tuitionInternational:31200,livingCost:16800,majors:["Architecture","Law","Medicine","Engineering","Economics","Psychology"],qsRank:9,usnewsRank:12},
  { name:"University of Sydney",nameZh:"悉尼大学",country:"Australia",city:"Sydney",state:"New South Wales",website:"https://www.sydney.edu.au",description:"Sydney is Australia's oldest university with stunning sandstone architecture.",type:"public",foundedYear:1850,studentCount:74000,acceptanceRate:30.0,avgIELTS:6.5,avgTOEFL:85,avgGPA:3.2,tuitionDomestic:10000,tuitionInternational:42000,livingCost:18000,majors:["Medicine","Law","Engineering","Business","Arts","Architecture"],qsRank:20,usnewsRank:28},
  { name:"University of British Columbia",nameZh:"英属哥伦比亚大学",country:"Canada",city:"Vancouver",state:"British Columbia",website:"https://www.ubc.ca",description:"UBC is a top Canadian university known for sustainability and Pacific Rim location.",type:"public",foundedYear:1908,studentCount:66000,acceptanceRate:52.0,avgSAT:1320,avgACT:29,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.5,tuitionDomestic:5600,tuitionInternational:42000,livingCost:15500,majors:["Forestry","Engineering","Computer Science","Business","Psychology","Environmental Science"],qsRank:35,usnewsRank:35},
  { name:"University of Hong Kong",nameZh:"香港大学",country:"Hong Kong",city:"Hong Kong",website:"https://www.hku.hk",description:"HKU is the oldest institution in Hong Kong, ranked among the world's most international.",type:"public",foundedYear:1911,studentCount:30000,acceptanceRate:20.0,avgSAT:1350,avgACT:30,avgIELTS:6.5,avgTOEFL:93,avgGPA:3.4,tuitionDomestic:42100,tuitionInternational:182000,livingCost:14000,majors:["Medicine","Law","Business","Engineering","Dentistry","Architecture"],qsRank:26,usnewsRank:55},
  { name:"Seoul National University",nameZh:"首尔大学",country:"South Korea",city:"Seoul",website:"https://www.snu.ac.kr",description:"SNU is South Korea's most prestigious national university.",type:"public",foundedYear:1946,studentCount:28200,acceptanceRate:15.0,avgSAT:1370,avgIELTS:6.0,avgTOEFL:80,avgGPA:3.3,tuitionDomestic:6000,tuitionInternational:12000,livingCost:10000,majors:["Engineering","Business","Medicine","Law","Computer Science","International Studies"],qsRank:41,usnewsRank:129},
  { name:"New York University",nameZh:"纽约大学",country:"United States",city:"New York",state:"New York",website:"https://www.nyu.edu",description:"NYU is the largest private university in the U.S. located in Greenwich Village.",type:"private",foundedYear:1831,studentCount:59000,acceptanceRate:12.8,avgSAT:1450,avgACT:32,avgIELTS:7.5,avgTOEFL:100,avgGPA:3.7,tuitionDomestic:58168,tuitionInternational:58168,livingCost:21000,majors:["Business","Film","Law","Arts","Computer Science","Economics"],qsRank:39,usnewsRank:31},
  { name:"University of Texas at Austin",nameZh:"德克萨斯大学奥斯汀分校",country:"United States",city:"Austin",state:"Texas",website:"https://www.utexas.edu",description:"UT Austin is the flagship of the UT system in vibrant Austin, Texas.",type:"public",foundedYear:1883,studentCount:52000,acceptanceRate:31.0,avgSAT:1350,avgACT:30,avgIELTS:6.5,avgTOEFL:79,avgGPA:3.8,tuitionDomestic:11800,tuitionInternational:42000,livingCost:13500,majors:["Engineering","Business","Computer Science","Film","Communications","Petroleum Engineering"],qsRank:52,usnewsRank:43},
  { name:"University of Washington",nameZh:"华盛顿大学",country:"United States",city:"Seattle",state:"Washington",website:"https://www.washington.edu",description:"UW is in the tech hub of Seattle with strong computer science and medicine.",type:"public",foundedYear:1861,studentCount:60000,acceptanceRate:48.0,avgSAT:1350,avgACT:30,avgIELTS:7.0,avgTOEFL:76,avgGPA:3.8,tuitionDomestic:12300,tuitionInternational:42000,livingCost:15000,majors:["Computer Science","Engineering","Medicine","Business","Biology","Nursing"],qsRank:54,usnewsRank:6},
  { name:"McGill University",nameZh:"麦吉尔大学",country:"Canada",city:"Montreal",state:"Quebec",website:"https://www.mcgill.ca",description:"McGill is one of Canada's most prestigious universities with a bilingual campus.",type:"public",foundedYear:1821,studentCount:40000,acceptanceRate:38.0,avgSAT:1390,avgACT:31,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.6,tuitionDomestic:2800,tuitionInternational:35000,livingCost:14000,majors:["Medicine","Law","Engineering","Arts","Science","Management"],qsRank:31,usnewsRank:54},
  { name:"University of Manchester",nameZh:"曼彻斯特大学",country:"United Kingdom",city:"Manchester",website:"https://www.manchester.ac.uk",description:"Manchester is a Russell Group university known for science and engineering research.",type:"public",foundedYear:1824,studentCount:40000,acceptanceRate:13.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:3.2,tuitionDomestic:9250,tuitionInternational:27000,livingCost:12000,majors:["Engineering","Computer Science","Business","Physics","Materials Science","Medicine"],qsRank:33,usnewsRank:63},
  { name:"University of New South Wales",nameZh:"新南威尔士大学",country:"Australia",city:"Sydney",state:"New South Wales",website:"https://www.unsw.edu.au",description:"UNSW is a Group of Eight university strong in engineering and business.",type:"public",foundedYear:1949,studentCount:63000,acceptanceRate:35.0,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.2,tuitionDomestic:10000,tuitionInternational:40000,livingCost:18000,majors:["Engineering","Business","Law","Computer Science","Architecture","Medicine"],qsRank:19,usnewsRank:37},
  { name:"University of Queensland",nameZh:"昆士兰大学",country:"Australia",city:"Brisbane",state:"Queensland",website:"https://www.uq.edu.au",description:"UQ is a Group of Eight university with a beautiful riverside campus.",type:"public",foundedYear:1909,studentCount:55000,acceptanceRate:40.0,avgIELTS:6.5,avgTOEFL:87,avgGPA:3.1,tuitionDomestic:10000,tuitionInternational:37000,livingCost:15000,majors:["Biotechnology","Medicine","Engineering","Business","Law","Environmental Science"],qsRank:44,usnewsRank:36},
  { name:"Australian National University",nameZh:"澳大利亚国立大学",country:"Australia",city:"Canberra",state:"ACT",website:"https://www.anu.edu.au",description:"ANU is Australia's top university for research, created by Parliament.",type:"public",foundedYear:1946,studentCount:21000,acceptanceRate:35.0,avgIELTS:6.5,avgTOEFL:80,avgGPA:3.3,tuitionDomestic:10000,tuitionInternational:39000,livingCost:16000,majors:["International Relations","Political Science","Law","Economics","Science","Arts"],qsRank:37,usnewsRank:62},
  { name:"Nanyang Technological University",nameZh:"南洋理工大学",country:"Singapore",city:"Singapore",website:"https://www.ntu.edu.sg",description:"NTU is a young research university with a beautiful garden campus.",type:"public",foundedYear:1991,studentCount:33000,acceptanceRate:30.0,avgSAT:1350,avgACT:30,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.4,tuitionDomestic:8200,tuitionInternational:28000,livingCost:12000,majors:["Engineering","Business","Computer Science","Art Design","Communication","Science"],qsRank:42,usnewsRank:30},
  { name:"King's College London",nameZh:"伦敦国王学院",country:"United Kingdom",city:"London",website:"https://www.kcl.ac.uk",description:"KCL is a founding college of the University of London, strong in law and humanities.",type:"public",foundedYear:1829,studentCount:33000,acceptanceRate:13.0,avgIELTS:6.5,avgTOEFL:92,avgGPA:3.3,tuitionDomestic:9250,tuitionInternational:28000,livingCost:16000,majors:["Law","Medicine","International Relations","History","Psychology","English"],qsRank:38,usnewsRank:33},
  { name:"Monash University",nameZh:"莫纳什大学",country:"Australia",city:"Melbourne",state:"Victoria",website:"https://www.monash.edu",description:"Monash is Australia's largest university, named after Sir John Monash.",type:"public",foundedYear:1958,studentCount:86000,acceptanceRate:45.0,avgIELTS:6.5,avgTOEFL:79,avgGPA:3.0,tuitionDomestic:10000,tuitionInternational:37000,livingCost:16000,majors:["Pharmacy","Engineering","Business","Medicine","Education","IT"],qsRank:43,usnewsRank:40},
  { name:"Zhejiang University",nameZh:"浙江大学",country:"China",city:"Hangzhou",state:"Zhejiang",website:"https://www.zju.edu.cn",description:"ZJU is a C9 League university in Hangzhou, excelling in engineering.",type:"public",foundedYear:1897,studentCount:54000,acceptanceRate:15.0,avgIELTS:6.0,avgTOEFL:85,avgGPA:3.3,tuitionDomestic:5000,tuitionInternational:24000,livingCost:7000,majors:["Engineering","Computer Science","Business","Medicine","Agriculture","Architecture"],qsRank:45,usnewsRank:93},
  { name:"Fudan University",nameZh:"复旦大学",country:"China",city:"Shanghai",website:"https://www.fudan.edu.cn",description:"Fudan is a C9 League university in Shanghai, known for humanities and medicine.",type:"public",foundedYear:1905,studentCount:34000,acceptanceRate:16.0,avgIELTS:6.0,avgTOEFL:85,avgGPA:3.3,tuitionDomestic:5000,tuitionInternational:24000,livingCost:9000,majors:["Medicine","Economics","Journalism","Law","Computer Science","Business"],qsRank:50,usnewsRank:116},
  { name:"Brown University",nameZh:"布朗大学",country:"United States",city:"Providence",state:"Rhode Island",website:"https://www.brown.edu",description:"Brown is an Ivy League known for its Open Curriculum without general education requirements.",type:"private",foundedYear:1764,studentCount:10700,acceptanceRate:5.1,avgSAT:1500,avgACT:34,avgIELTS:8.0,avgTOEFL:100,avgGPA:4.08,tuitionDomestic:65146,tuitionInternational:65146,livingCost:17900,majors:["Computer Science","Economics","Biology","English","International Relations","Engineering"],qsRank:51,usnewsRank:101},
  { name:"Dartmouth College",nameZh:"达特茅斯学院",country:"United States",city:"Hanover",state:"New Hampshire",website:"https://www.dartmouth.edu",description:"Dartmouth is an Ivy League with a strong undergraduate focus and D-Plan quarter system.",type:"private",foundedYear:1769,studentCount:6600,acceptanceRate:6.2,avgSAT:1500,avgACT:33,avgIELTS:7.0,avgTOEFL:100,avgGPA:4.06,tuitionDomestic:62430,tuitionInternational:62430,livingCost:18000,majors:["Economics","Government","Engineering","Computer Science","Biology","History"],qsRank:53,usnewsRank:176},
  { name:"University of Wisconsin-Madison",nameZh:"威斯康星大学麦迪逊分校",country:"United States",city:"Madison",state:"Wisconsin",website:"https://www.wisc.edu",description:"UW-Madison is a top public research university strong in life sciences.",type:"public",foundedYear:1848,studentCount:49000,acceptanceRate:54.0,avgSAT:1380,avgACT:30,avgIELTS:6.5,avgTOEFL:80,avgGPA:3.8,tuitionDomestic:10900,tuitionInternational:40600,livingCost:13000,majors:["Engineering","Computer Science","Business","Biology","Economics","Psychology"],qsRank:55,usnewsRank:39},
  // Additional universities without QS/US News rankings
  { name:"University of Amsterdam",nameZh:"阿姆斯特丹大学",country:"Netherlands",city:"Amsterdam",website:"https://www.uva.nl",description:"UvA is one of Europe's top research universities with a strong international focus.",type:"public",foundedYear:1632,studentCount:35000,acceptanceRate:25.0,avgIELTS:6.5,avgTOEFL:92,avgGPA:3.3,tuitionDomestic:2200,tuitionInternational:14000,livingCost:13000,majors:["Business","Law","Psychology","Media Studies","Economics","Computer Science"]},
  { name:"Technical University of Munich",nameZh:"慕尼黑工业大学",country:"Germany",city:"Munich",website:"https://www.tum.de",description:"TUM is Germany's top technical university with strong industry connections.",type:"public",foundedYear:1868,studentCount:48000,acceptanceRate:30.0,avgIELTS:6.5,avgTOEFL:88,avgGPA:3.2,tuitionDomestic:300,tuitionInternational:6000,livingCost:12000,majors:["Engineering","Computer Science","Physics","Mathematics","Architecture","Business"]},
  { name:"LMU Munich",nameZh:"慕尼黑大学",country:"Germany",city:"Munich",website:"https://www.lmu.de",description:"LMU is one of Europe's leading research universities with a 500-year history.",type:"public",foundedYear:1472,studentCount:52000,acceptanceRate:35.0,avgIELTS:6.5,avgTOEFL:88,avgGPA:3.1,tuitionDomestic:300,tuitionInternational:6000,livingCost:12000,majors:["Medicine","Law","Physics","Philosophy","Economics","Biology"]},
  { name:"University of Copenhagen",nameZh:"哥本哈根大学",country:"Denmark",city:"Copenhagen",website:"https://www.ku.dk",description:"UCPH is Denmark's largest and oldest university with strong research output.",type:"public",foundedYear:1479,studentCount:38000,acceptanceRate:30.0,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.2,tuitionDomestic:0,tuitionInternational:15000,livingCost:14000,majors:["Life Sciences","Medicine","Law","Computer Science","Humanities","Economics"]},
  { name:"University of Helsinki",nameZh:"赫尔辛基大学",country:"Finland",city:"Helsinki",website:"https://www.helsinki.fi",description:"The University of Helsinki is Finland's oldest and largest university.",type:"public",foundedYear:1640,studentCount:31000,acceptanceRate:20.0,avgIELTS:6.5,avgTOEFL:92,avgGPA:3.2,tuitionDomestic:0,tuitionInternational:15000,livingCost:11000,majors:["Computer Science","Medicine","Law","Environmental Science","Education","Arts"]},
  { name:"Leiden University",nameZh:"莱顿大学",country:"Netherlands",city:"Leiden",website:"https://www.universiteitleiden.nl",description:"Leiden is the oldest university in the Netherlands, strong in humanities and law.",type:"public",foundedYear:1575,studentCount:30000,acceptanceRate:30.0,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.2,tuitionDomestic:2200,tuitionInternational:13000,livingCost:12500,majors:["Law","International Relations","Medicine","History","Political Science","Archaeology"]},
  { name:"University of Zurich",nameZh:"苏黎世大学",country:"Switzerland",city:"Zurich",website:"https://www.uzh.ch",description:"UZH is Switzerland's largest university with strong research across disciplines.",type:"public",foundedYear:1833,studentCount:26000,acceptanceRate:35.0,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.1,tuitionDomestic:1500,tuitionInternational:3000,livingCost:17000,majors:["Medicine","Law","Economics","Biology","Computer Science","Psychology"]},
  { name:"KU Leuven",nameZh:"鲁汶大学",country:"Belgium",city:"Leuven",website:"https://www.kuleuven.be",description:"KU Leuven is Belgium's largest and highest-ranked university, founded in 1425.",type:"public",foundedYear:1425,studentCount:60000,acceptanceRate:40.0,avgIELTS:6.5,avgTOEFL:85,avgGPA:3.0,tuitionDomestic:1000,tuitionInternational:7000,livingCost:11000,majors:["Engineering","Medicine","Law","Business","Psychology","Computer Science"]},
  { name:"Uppsala University",nameZh:"乌普萨拉大学",country:"Sweden",city:"Uppsala",website:"https://www.uu.se",description:"Uppsala is Sweden's oldest university, founded in 1477, known for life sciences.",type:"public",foundedYear:1477,studentCount:45000,acceptanceRate:30.0,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.1,tuitionDomestic:0,tuitionInternational:16000,livingCost:11000,majors:["Life Sciences","Medicine","Law","Computer Science","Peace Studies","Engineering"]},
  { name:"University of Oslo",nameZh:"奥斯陆大学",country:"Norway",city:"Oslo",website:"https://www.uio.no",description:"UiO is Norway's oldest and largest university with strong humanities and sciences.",type:"public",foundedYear:1811,studentCount:28000,acceptanceRate:30.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:3.0,tuitionDomestic:0,tuitionInternational:0,livingCost:15000,majors:["Medicine","Law","Humanities","Computer Science","Mathematics","Social Sciences"]},
  { name:"University of Vienna",nameZh:"维也纳大学",country:"Austria",city:"Vienna",website:"https://www.univie.ac.at",description:"University of Vienna is one of the oldest and largest universities in Europe.",type:"public",foundedYear:1365,studentCount:90000,acceptanceRate:45.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:2.8,tuitionDomestic:400,tuitionInternational:1500,livingCost:12000,majors:["Law","Medicine","Psychology","History","Computer Science","Philosophy"]},
  { name:"University of Warsaw",nameZh:"华沙大学",country:"Poland",city:"Warsaw",website:"https://www.uw.edu.pl",description:"UW is Poland's largest and top-ranked university with strong international programs.",type:"public",foundedYear:1816,studentCount:50000,acceptanceRate:40.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:3.0,tuitionDomestic:0,tuitionInternational:5000,livingCost:7000,majors:["International Relations","Computer Science","Law","Economics","Management","English"]},
  { name:"Charles University",nameZh:"查理大学",country:"Czech Republic",city:"Prague",website:"https://www.cuni.cz",description:"Charles University is the oldest university in Central Europe, founded in 1348.",type:"public",foundedYear:1348,studentCount:50000,acceptanceRate:45.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:2.8,tuitionDomestic:0,tuitionInternational:8000,livingCost:8000,majors:["Medicine","Law","Computer Science","Humanities","Pharmacy","Social Sciences"]},
  { name:"University of Barcelona",nameZh:"巴塞罗那大学",country:"Spain",city:"Barcelona",website:"https://www.ub.edu",description:"UB is Spain's top-ranked university located in vibrant Barcelona.",type:"public",foundedYear:1450,studentCount:63000,acceptanceRate:50.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:2.8,tuitionDomestic:2000,tuitionInternational:5000,livingCost:11000,majors:["Medicine","Law","Business","Arts","Architecture","Biology"]},
  { name:"Sapienza University of Rome",nameZh:"罗马大学",country:"Italy",city:"Rome",website:"https://www.uniroma1.it",description:"Sapienza is one of Europe's largest universities by enrollment, founded in 1303.",type:"public",foundedYear:1303,studentCount:112000,acceptanceRate:50.0,avgIELTS:6.0,avgTOEFL:78,avgGPA:2.7,tuitionDomestic:2000,tuitionInternational:3000,livingCost:11000,majors:["Architecture","Engineering","Medicine","Physics","Law","Classics"]},
  { name:"University of Cape Town",nameZh:"开普敦大学",country:"South Africa",city:"Cape Town",website:"https://www.uct.ac.za",description:"UCT is Africa's top-ranked university located at the foot of Table Mountain.",type:"public",foundedYear:1829,studentCount:29000,acceptanceRate:35.0,avgIELTS:6.5,avgTOEFL:88,avgGPA:3.0,tuitionDomestic:5000,tuitionInternational:8000,livingCost:8000,majors:["Medicine","Law","Engineering","Commerce","Humanities","Science"]},
  { name:"University of Sao Paulo",nameZh:"圣保罗大学",country:"Brazil",city:"Sao Paulo",website:"https://www5.usp.br",description:"USP is Brazil's largest and most prestigious public university.",type:"public",foundedYear:1934,studentCount:92000,acceptanceRate:15.0,avgIELTS:6.0,avgTOEFL:78,avgGPA:3.0,tuitionDomestic:0,tuitionInternational:0,livingCost:8000,majors:["Medicine","Engineering","Law","Business","Architecture","Computer Science"]},
  { name:"University of Buenos Aires",nameZh:"布宜诺斯艾利斯大学",country:"Argentina",city:"Buenos Aires",website:"https://www.uba.ar",description:"UBA is Argentina's largest and most prestigious public university.",type:"public",foundedYear:1821,studentCount:300000,acceptanceRate:60.0,avgIELTS:5.5,avgTOEFL:70,avgGPA:2.5,tuitionDomestic:0,tuitionInternational:0,livingCost:7000,majors:["Medicine","Law","Engineering","Economics","Architecture","Social Sciences"]},
  { name:"Tecnologico de Monterrey",nameZh:"蒙特雷科技大学",country:"Mexico",city:"Monterrey",state:"Nuevo Leon",website:"https://www.tec.mx",description:"Tec is Mexico's top private university, known for entrepreneurship and engineering.",type:"private",foundedYear:1943,studentCount:90000,acceptanceRate:50.0,avgSAT:1250,avgIELTS:6.5,avgTOEFL:80,avgGPA:3.2,tuitionDomestic:14000,tuitionInternational:18000,livingCost:9000,majors:["Engineering","Business","Computer Science","Architecture","Medicine","Design"]},
  { name:"KAIST",nameZh:"韩国科学技术院",country:"South Korea",city:"Daejeon",website:"https://www.kaist.ac.kr",description:"KAIST is South Korea's premier science and technology research university.",type:"public",foundedYear:1971,studentCount:11000,acceptanceRate:15.0,avgSAT:1450,avgIELTS:6.5,avgTOEFL:95,avgGPA:3.5,tuitionDomestic:4000,tuitionInternational:9000,livingCost:9000,majors:["Computer Science","Engineering","Physics","Mathematics","Chemistry","Business"]},
  { name:"Tokyo Institute of Technology",nameZh:"东京工业大学",country:"Japan",city:"Tokyo",website:"https://www.titech.ac.jp",description:"Tokyo Tech is Japan's top institution for science and technology.",type:"public",foundedYear:1881,studentCount:10000,acceptanceRate:20.0,avgSAT:1400,avgIELTS:6.0,avgTOEFL:85,avgGPA:3.3,tuitionDomestic:535800,tuitionInternational:535800,livingCost:12000,majors:["Engineering","Computer Science","Physics","Chemistry","Mathematics","Architecture"]},
  { name:"Kyoto University",nameZh:"京都大学",country:"Japan",city:"Kyoto",website:"https://www.kyoto-u.ac.jp",description:"Kyoto University is Japan's second-oldest imperial university, with numerous Nobel laureates.",type:"public",foundedYear:1897,studentCount:23000,acceptanceRate:25.0,avgSAT:1380,avgIELTS:6.0,avgTOEFL:85,avgGPA:3.3,tuitionDomestic:535800,tuitionInternational:535800,livingCost:11000,majors:["Science","Engineering","Medicine","Law","Economics","Pharmacy"]},
  { name:"National Taiwan University",nameZh:"国立台湾大学",country:"Taiwan",city:"Taipei",website:"https://www.ntu.edu.tw",description:"NTU is Taiwan's most prestigious university, strong in engineering and medicine.",type:"public",foundedYear:1928,studentCount:32000,acceptanceRate:25.0,avgSAT:1300,avgIELTS:6.0,avgTOEFL:80,avgGPA:3.2,tuitionDomestic:3000,tuitionInternational:8000,livingCost:9000,majors:["Engineering","Medicine","Law","Business","Computer Science","Electrical Engineering"]},
  { name:"Indian Institute of Technology Bombay",nameZh:"印度理工学院孟买分校",country:"India",city:"Mumbai",state:"Maharashtra",website:"https://www.iitb.ac.in",description:"IIT Bombay is India's premier engineering institution with world-class research.",type:"public",foundedYear:1958,studentCount:12000,acceptanceRate:0.5,avgSAT:1400,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.5,tuitionDomestic:2000,tuitionInternational:12000,livingCost:5000,majors:["Computer Science","Engineering","Mathematics","Physics","Design","Business"]},
  { name:"Indian Institute of Technology Delhi",nameZh:"印度理工学院德里分校",country:"India",city:"New Delhi",website:"https://www.iitd.ac.in",description:"IIT Delhi is one of India's top engineering and technology institutions.",type:"public",foundedYear:1961,studentCount:11000,acceptanceRate:0.5,avgSAT:1380,avgIELTS:6.5,avgTOEFL:90,avgGPA:3.4,tuitionDomestic:2000,tuitionInternational:12000,livingCost:5000,majors:["Computer Science","Engineering","Mathematics","Textile Engineering","Physics","Business"]},
  { name:"University of Malaya",nameZh:"马来亚大学",country:"Malaysia",city:"Kuala Lumpur",website:"https://www.um.edu.my",description:"UM is Malaysia's oldest and top-ranked university.",type:"public",foundedYear:1905,studentCount:25000,acceptanceRate:35.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:3.0,tuitionDomestic:3000,tuitionInternational:10000,livingCost:6000,majors:["Engineering","Medicine","Law","Business","Computer Science","Arts"]},
  { name:"Chulalongkorn University",nameZh:"朱拉隆功大学",country:"Thailand",city:"Bangkok",website:"https://www.chula.ac.th",description:"Chulalongkorn is Thailand's oldest and most prestigious university.",type:"public",foundedYear:1917,studentCount:38000,acceptanceRate:25.0,avgIELTS:6.0,avgTOEFL:79,avgGPA:3.0,tuitionDomestic:2000,tuitionInternational:8000,livingCost:6000,majors:["Engineering","Medicine","Business","Architecture","Law","Arts"]},
  { name:"University of the Philippines Diliman",nameZh:"菲律宾大学迪里曼分校",country:"Philippines",city:"Quezon City",website:"https://www.upd.edu.ph",description:"UP Diliman is the flagship campus of the Philippines' national university.",type:"public",foundedYear:1908,studentCount:26000,acceptanceRate:15.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:2.8,tuitionDomestic:2000,tuitionInternational:5000,livingCost:5000,majors:["Engineering","Law","Medicine","Business","Computer Science","Fine Arts"]},
  { name:"Pontifical Catholic University of Chile",nameZh:"智利天主教大学",country:"Chile",city:"Santiago",website:"https://www.uc.cl",description:"UC Chile is Latin America's top-ranked university known for engineering and business.",type:"private",foundedYear:1888,studentCount:30000,acceptanceRate:30.0,avgIELTS:6.0,avgTOEFL:78,avgGPA:3.0,tuitionDomestic:7000,tuitionInternational:12000,livingCost:9000,majors:["Engineering","Business","Law","Medicine","Architecture","Education"]},
  { name:"University of Auckland",nameZh:"奥克兰大学",country:"New Zealand",city:"Auckland",website:"https://www.auckland.ac.nz",description:"The University of Auckland is New Zealand's largest and highest-ranked university.",type:"public",foundedYear:1883,studentCount:43000,acceptanceRate:45.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:3.0,tuitionDomestic:7000,tuitionInternational:35000,livingCost:14000,majors:["Engineering","Medicine","Business","Law","Computer Science","Architecture"]},
  { name:"University of Otago",nameZh:"奥塔哥大学",country:"New Zealand",city:"Dunedin",website:"https://www.otago.ac.nz",description:"Otago is New Zealand's oldest university, renowned for health sciences.",type:"public",foundedYear:1869,studentCount:21000,acceptanceRate:50.0,avgIELTS:6.0,avgTOEFL:80,avgGPA:2.8,tuitionDomestic:7000,tuitionInternational:32000,livingCost:12000,majors:["Medicine","Dentistry","Law","Pharmacy","Physical Education","Science"]},
  { name:"Dublin City University",nameZh:"都柏林城市大学",country:"Ireland",city:"Dublin",website:"https://www.dcu.ie",description:"DCU is known for innovation, entrepreneurship, and strong industry links.",type:"public",foundedYear:1980,studentCount:17000,acceptanceRate:40.0,avgIELTS:6.5,avgTOEFL:88,avgGPA:3.0,tuitionDomestic:3000,tuitionInternational:15000,livingCost:13000,majors:["Computer Science","Engineering","Business","Communications","Education","Biotechnology"]},
  { name:"University of St Andrews",nameZh:"圣安德鲁斯大学",country:"United Kingdom",city:"St Andrews",website:"https://www.st-andrews.ac.uk",description:"St Andrews is Scotland's oldest university, known for tradition and academic excellence.",type:"public",foundedYear:1413,studentCount:10000,acceptanceRate:8.5,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.5,tuitionDomestic:9250,tuitionInternational:28000,livingCost:12000,majors:["International Relations","Computer Science","English","Physics","Philosophy","History"]},
  { name:"Lancaster University",nameZh:"兰卡斯特大学",country:"United Kingdom",city:"Lancaster",website:"https://www.lancaster.ac.uk",description:"Lancaster is a collegiate university known for high student satisfaction and research.",type:"public",foundedYear:1964,studentCount:15000,acceptanceRate:18.0,avgIELTS:6.5,avgTOEFL:87,avgGPA:3.2,tuitionDomestic:9250,tuitionInternational:23000,livingCost:10000,majors:["Business","Computer Science","Engineering","Law","English","Environmental Science"]},
  { name:"George Washington University",nameZh:"乔治华盛顿大学",country:"United States",city:"Washington",state:"D.C.",website:"https://www.gwu.edu",description:"GWU is located in the heart of D.C., strong in international affairs and political science.",type:"private",foundedYear:1821,studentCount:27000,acceptanceRate:43.0,avgSAT:1370,avgACT:31,avgIELTS:7.0,avgTOEFL:90,avgGPA:3.7,tuitionDomestic:62000,tuitionInternational:62000,livingCost:18000,majors:["International Affairs","Political Science","Law","Business","Medicine","Journalism"]},
  { name:"Boston University",nameZh:"波士顿大学",country:"United States",city:"Boston",state:"Massachusetts",website:"https://www.bu.edu",description:"BU is a private research university along the Charles River with global reach.",type:"private",foundedYear:1839,studentCount:34000,acceptanceRate:18.9,avgSAT:1420,avgACT:32,avgIELTS:7.0,avgTOEFL:90,avgGPA:3.7,tuitionDomestic:61000,tuitionInternational:61000,livingCost:17000,majors:["Business","Communications","Engineering","Computer Science","Psychology","Medicine"]},
  { name:"Rice University",nameZh:"莱斯大学",country:"United States",city:"Houston",state:"Texas",website:"https://www.rice.edu",description:"Rice is a private research university with a residential college system in Houston.",type:"private",foundedYear:1912,studentCount:8000,acceptanceRate:8.7,avgSAT:1500,avgACT:34,avgIELTS:7.0,avgTOEFL:100,avgGPA:4.0,tuitionDomestic:54000,tuitionInternational:54000,livingCost:16000,majors:["Engineering","Computer Science","Architecture","Music","Business","Natural Sciences"]},
  { name:"Vanderbilt University",nameZh:"范德堡大学",country:"United States",city:"Nashville",state:"Tennessee",website:"https://www.vanderbilt.edu",description:"Vanderbilt is a private research university in Nashville known for education and medicine.",type:"private",foundedYear:1873,studentCount:14000,acceptanceRate:6.7,avgSAT:1500,avgACT:34,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.9,tuitionDomestic:60000,tuitionInternational:60000,livingCost:17000,majors:["Education","Medicine","Engineering","Law","Economics","Music"]},
  { name:"University of Southern California",nameZh:"南加州大学",country:"United States",city:"Los Angeles",state:"California",website:"https://www.usc.edu",description:"USC is a private research university in LA, known for film, business, and engineering.",type:"private",foundedYear:1880,studentCount:49000,acceptanceRate:12.0,avgSAT:1440,avgACT:32,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.8,tuitionDomestic:63000,tuitionInternational:63000,livingCost:17500,majors:["Film","Business","Engineering","Computer Science","Communications","Architecture"]},
  { name:"Carnegie Mellon University",nameZh:"卡内基梅隆大学",country:"United States",city:"Pittsburgh",state:"Pennsylvania",website:"https://www.cmu.edu",description:"CMU is renowned for computer science, engineering, and fine arts.",type:"private",foundedYear:1900,studentCount:15000,acceptanceRate:13.5,avgSAT:1500,avgACT:34,avgIELTS:7.5,avgTOEFL:102,avgGPA:3.9,tuitionDomestic:61000,tuitionInternational:61000,livingCost:16000,majors:["Computer Science","Engineering","Drama","Business","Design","Robotics"]},
  { name:"Emory University",nameZh:"埃默里大学",country:"United States",city:"Atlanta",state:"Georgia",website:"https://www.emory.edu",description:"Emory is a private research university in Atlanta strong in medicine and liberal arts.",type:"private",foundedYear:1836,studentCount:16000,acceptanceRate:15.6,avgSAT:1450,avgACT:33,avgIELTS:7.0,avgTOEFL:100,avgGPA:3.9,tuitionDomestic:58000,tuitionInternational:58000,livingCost:16500,majors:["Medicine","Business","Law","Nursing","Public Health","Biology"]},
  { name:"University of Illinois Urbana-Champaign",nameZh:"伊利诺伊大学厄巴纳-香槟分校",country:"United States",city:"Champaign",state:"Illinois",website:"https://www.illinois.edu",description:"UIUC is a top public research university, especially strong in engineering and CS.",type:"public",foundedYear:1867,studentCount:51000,acceptanceRate:63.0,avgSAT:1350,avgACT:30,avgIELTS:6.5,avgTOEFL:79,avgGPA:3.7,tuitionDomestic:17000,tuitionInternational:38000,livingCost:13000,majors:["Computer Science","Engineering","Business","Accounting","Architecture","Psychology"]},
  { name:"Penn State University",nameZh:"宾州州立大学",country:"United States",city:"University Park",state:"Pennsylvania",website:"https://www.psu.edu",description:"Penn State is a major public research university with one of the largest alumni networks.",type:"public",foundedYear:1855,studentCount:46000,acceptanceRate:54.0,avgSAT:1300,avgACT:29,avgIELTS:6.5,avgTOEFL:80,avgGPA:3.6,tuitionDomestic:19000,tuitionInternational:37000,livingCost:13000,majors:["Engineering","Business","Computer Science","Communications","Education","Agriculture"]},
];

export async function GET() {
  try {
    await prisma.ranking.deleteMany();
    await prisma.major.deleteMany();
    await prisma.university.deleteMany();
    await prisma.testQuestion.deleteMany();
    await prisma.testCategory.deleteMany();

    const adminPassword = await bcrypt.hash("admin123", 12);
    const teacherPassword = await bcrypt.hash("teacher123", 12);
    const studentPassword = await bcrypt.hash("student123", 12);
    await prisma.user.upsert({ where: { email: "admin@upath.com" }, update: {}, create: { name: "System Admin", email: "admin@upath.com", password: adminPassword, role: "ADMIN" } });
    await prisma.user.upsert({ where: { email: "teacher@upath.com" }, update: {}, create: { name: "Zhang Laoshi", email: "teacher@upath.com", password: teacherPassword, role: "TEACHER" } });
    await prisma.user.upsert({ where: { email: "student@upath.com" }, update: {}, create: { name: "Xiao Ming", email: "student@upath.com", password: studentPassword, role: "STUDENT" } });

    let uniCount = 0;
    for (const u of UNIS) {
      const uni = await prisma.university.create({
        data: {
          name: u.name, nameZh: u.nameZh, country: u.country, city: u.city, state: u.state || null,
          website: u.website, description: u.description, type: u.type, foundedYear: u.foundedYear,
          studentCount: u.studentCount, acceptanceRate: u.acceptanceRate,
          avgSAT: u.avgSAT || null, avgACT: u.avgACT || null, avgIELTS: u.avgIELTS || null,
          avgTOEFL: u.avgTOEFL || null, avgGPA: u.avgGPA || null,
          tuitionDomestic: u.tuitionDomestic, tuitionInternational: u.tuitionInternational,
          livingCost: u.livingCost,
        },
      });
      // Create majors
      for (const m of u.majors) {
        await prisma.major.create({
          data: { name: m, universityId: uni.id, category: ["Computer Science","Engineering","Electrical Engineering","Mechanical Engineering","Chemical Engineering","Aerospace Engineering","Robotics"].includes(m) ? "Engineering" : "Arts & Sciences", degreeLevel: "Bachelor" },
        });
      }
      // Create rankings if available
      if (u.qsRank) {
        await prisma.ranking.create({ data: { universityId: uni.id, rank: u.qsRank, year: 2025, source: "QS" } });
      }
      if (u.usnewsRank) {
        await prisma.ranking.create({ data: { universityId: uni.id, rank: u.usnewsRank, year: 2025, source: "US_NEWS" } });
      }
      uniCount++;
    }

    await prisma.testCategory.createMany({
      data: [
        { name: "SAT", description: "SAT standardized test" },
        { name: "IELTS", description: "IELTS English test" },
        { name: "TOEFL", description: "TOEFL English test" },
        { name: "ACT", description: "ACT standardized test" },
      ],
    });

    return NextResponse.json({ success: true, universities: uniCount });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
